print("1a")
print("Is float(4.6) = int(4.6)?")
print(float(4.6) == int(4.6))
print('''float(4.6) and int(4.6) are different because the 'int' in 'int(4.6)' 
converts 4.6 to 4 but float(4.6) does not change the number''')
print(" ")
print("1b")
print("What is int(3.7)?")
print(int(3.7))
print("int(3.7) returns " + str(int(3.7)))
print(" ")
print("1c")
print('Does int("4.5") and/or int("4 and 5") work?')
print('int("4.5"):')
print('Is a ValueError because "4.5" is text type data put into a numbers function')
print('int("4 and 5"):')
print('Is a ValueError because again, there is text type data being put into a numbers function.')
print(" ")
print("1d")
print('What happens when you try float("three point six") or float("three")?')
print('float("three point six"):')
print('Is a ValueError because text type data is being plugged into a numbers function')
print('float ("three"):')
print('Is a ValueError because text type data is being plugged into a numbers function')